### ISSUE TITLE
Support pre-render on Hosting

### ISSUE THREAD

**Issue by douglascorrea** [steida/firebase#9] opened 2016-06-06 21:18 UTC
Some discussions were done here: https://github.com/firebase/firebase-tools/issues/33

**Comment by steida** [comment] 2016-06-07 21:49
If you want real prerendering, use Heroku or something else. github.com/este/este is fully prepared for that. I think prerender.io and similars are nasty workarounds. With React and Este, the right solution is easy.

**Comment by douglascorrea** [comment] 2016-06-07 21:56
@steida I know that is possible and server side rendering is much better then prerendering.

But what I put here as an "issue" for Firebase is, as far they are trying to provide an "complete solution" for web and mobile apps and that includes static hosting (as it is already included), it would be a very nice feature to have on their hosting solution.

Since [Divshot](https://divshot.com/), which they recently acquired, provided this feature, they have the way to perform it.

Also some of competitors on Static hosting already provide it as [Netilify](https://www.netlify.com)

**Comment by steida** [comment] 2016-06-07 22:07
They are not able to ship Firebase 3 without serious regressions and bugs. Guess how long it takes to implement you suggested? I closed it because it's not reasonable to expect such feature in next two years at least.

**Comment by jwngr** [comment] 2016-06-07 22:54
Daniel, I would consider re-opening this issue. I'm trying my best to engage with this issue tracker you set up and Douglas is just trying to take part in it too. If you are going to close issues for valid feature requests, then this is more a personal tracker than a community one like you said it was, and I'll stop commenting on it. And I'm sure Douglas is less likely to engage with it now too after your response.

I realize you are upset with the `3.x.x` release and I am fighting tirelessly every day both with internal and external developers to resolve the great issues you've been raising. I literally just got out of a meeting where I proposed a solution for isomorphic apps using Firebase. But it makes my job easier when you are on my side and not throwing barbs at my team every chance you get. It's hard to share issues you raise with other Firebasers since they get tripped up on the negative comments littered amongst them.

Yes, we want to support pre-rendering on Hosting. Yes, it is not as good as server-side rendering like that found in Este. But there have been other higher priority things than pre-rendering that we've been working on (like the twelve new products we shipped at I/O). But this is totally a valid feature request and something we want to support.

**Comment by jwngr** [comment] 2016-06-07 22:58
Thanks!

**Comment by steida** [comment] 2016-06-07 23:00
Sure I can move ownership to Firebase team or you anytime.

**Comment by douglascorrea** [comment] 2016-06-07 23:22
Thanks @jwngr and @steida to make this repo as good as it could be

**Closed** 2016-10-25 22:29 UTC
Labels: enhancement
